""" 财务数据 ORM 表定义：三张报表 + 财务指标 + 业绩预告/快报 + 分红 + 审计意见 + 主营业务 + 披露日期 """
from orm_models.base import Base
from sqlalchemy import Column, Float, String


class IncomeStatement(Base):
    """ 利润表 income_vip """
    __tablename__ = "income_statement"
    # 复合主键：ts_code + end_date + report_type
    ts_code_end_date_report_type = Column(String, primary_key=True)
    ts_code        = Column(String, index=True, comment='TS股票代码')
    ann_date       = Column(String, index=True, comment='公告日期')
    f_ann_date     = Column(String, comment='实际公告日期')
    end_date       = Column(String, index=True, comment='报告期')
    report_type    = Column(String, index=True, comment='报告类型')
    comp_type      = Column(String, comment='公司类型')
    end_type       = Column(String, comment='报告期类型')
    basic_eps      = Column(Float, comment='基本每股收益')
    diluted_eps    = Column(Float, comment='稀释每股收益')
    total_revenue  = Column(Float, comment='营业总收入')
    revenue        = Column(Float, comment='营业收入')
    int_income     = Column(Float, comment='利息收入')
    prem_earned    = Column(Float, comment='已赚保费')
    comm_income    = Column(Float, comment='手续费及佣金收入')
    n_commis_income      = Column(Float, comment='手续费及佣金净收入')
    n_oth_income         = Column(Float, comment='其他经营净收益')
    n_oth_b_income       = Column(Float, comment='加:其他业务净收益')
    prem_income          = Column(Float, comment='保险业务收入')
    out_prem             = Column(Float, comment='减:分出保费')
    une_prem_reser       = Column(Float, comment='提取未到期责任准备金')
    reins_income         = Column(Float, comment='其中:分保费收入')
    n_sec_tb_income      = Column(Float, comment='代理买卖证券业务净收入')
    n_sec_uw_income      = Column(Float, comment='证券承销业务净收入')
    n_asset_mg_income    = Column(Float, comment='受托客户资产管理业务净收入')
    oth_b_income         = Column(Float, comment='其他业务收入')
    fv_value_chg_gain    = Column(Float, comment='加:公允价值变动净收益')
    invest_income        = Column(Float, comment='加:投资净收益')
    ass_invest_income    = Column(Float, comment='其中:对联营企业和合营企业的投资收益')
    forex_gain           = Column(Float, comment='加:汇兑净收益')
    total_cogs           = Column(Float, comment='营业总成本')
    oper_cost            = Column(Float, comment='减:营业成本')
    int_exp              = Column(Float, comment='减:利息支出')
    comm_exp             = Column(Float, comment='减:手续费及佣金支出')
    biz_tax_surchg       = Column(Float, comment='减:营业税金及附加')
    sell_exp             = Column(Float, comment='减:销售费用')
    admin_exp            = Column(Float, comment='减:管理费用')
    fin_exp              = Column(Float, comment='减:财务费用')
    assets_impair_loss   = Column(Float, comment='减:资产减值损失')
    prem_refund          = Column(Float, comment='退保金')
    compens_payout       = Column(Float, comment='赔付总支出')
    reser_insur_liab     = Column(Float, comment='提取保险责任准备金')
    div_payt             = Column(Float, comment='保户红利支出')
    reins_exp            = Column(Float, comment='分保费用')
    oper_exp             = Column(Float, comment='营业支出')
    compens_payout_refu  = Column(Float, comment='减:摊回赔付支出')
    insur_reser_refu     = Column(Float, comment='减:摊回保险责任准备金')
    reins_cost_refund    = Column(Float, comment='减:摊回分保费用')
    other_bus_cost       = Column(Float, comment='其他业务成本')
    operate_profit       = Column(Float, comment='营业利润')
    non_oper_income      = Column(Float, comment='加:营业外收入')
    non_oper_exp         = Column(Float, comment='减:营业外支出')
    nca_disploss         = Column(Float, comment='其中:减:非流动资产处置净损失')
    total_profit         = Column(Float, comment='利润总额')
    income_tax           = Column(Float, comment='所得税费用')
    n_income             = Column(Float, comment='净利润(含少数股东损益)')
    n_income_attr_p      = Column(Float, comment='净利润(不含少数股东损益)')
    minority_gain        = Column(Float, comment='少数股东损益')
    oth_compr_income     = Column(Float, comment='其他综合收益')
    t_compr_income       = Column(Float, comment='综合收益总额')
    compr_inc_attr_p     = Column(Float, comment='归属于母公司(或股东)的综合收益总额')
    compr_inc_attr_m_s   = Column(Float, comment='归属于少数股东的综合收益总额')
    ebit                 = Column(Float, comment='息税前利润')
    ebitda               = Column(Float, comment='息税折旧摊销前利润')
    insurance_exp        = Column(Float, comment='保险业务支出')
    undist_profit        = Column(Float, comment='年初未分配利润')
    distable_profit      = Column(Float, comment='可分配利润')
    rd_exp               = Column(Float, comment='研发费用')
    fin_exp_int_exp      = Column(Float, comment='财务费用:利息费用')
    fin_exp_int_inc      = Column(Float, comment='财务费用:利息收入')
    transfer_surplus_rese      = Column(Float, comment='盈余公积转入')
    transfer_housing_imprest   = Column(Float, comment='住房周转金转入')
    transfer_oth               = Column(Float, comment='其他转入')
    adj_lossgain               = Column(Float, comment='调整以前年度损益')
    withdra_legal_surplus      = Column(Float, comment='提取法定盈余公积')
    withdra_legal_pubfund      = Column(Float, comment='提取法定公益金')
    withdra_biz_devfund        = Column(Float, comment='提取企业发展基金')
    withdra_rese_fund          = Column(Float, comment='提取储备基金')
    withdra_oth_ersu           = Column(Float, comment='提取任意盈余公积金')
    workers_welfare            = Column(Float, comment='职工奖金福利')
    distr_profit_shrhder       = Column(Float, comment='可供股东分配的利润')
    prfshare_payable_dvd       = Column(Float, comment='应付优先股股利')
    comshare_payable_dvd       = Column(Float, comment='应付普通股股利')
    capit_comstock_div         = Column(Float, comment='转作股本的普通股股利')
    net_after_nr_lp_correct    = Column(Float, comment='扣除非经常性损益后的净利润（更正前）')
    credit_impa_loss           = Column(Float, comment='信用减值损失')
    net_expo_hedging_benefits  = Column(Float, comment='净敞口套期收益')
    oth_impair_loss_assets     = Column(Float, comment='其他资产减值损失')
    total_opcost               = Column(Float, comment='营业总成本（二）')
    amodcost_fin_assets        = Column(Float, comment='以摊余成本计量的金融资产终止确认收益')
    oth_income                 = Column(Float, comment='其他收益')
    asset_disp_income          = Column(Float, comment='资产处置收益')
    continued_net_profit       = Column(Float, comment='持续经营净利润')
    end_net_profit             = Column(Float, comment='终止经营净利润')
    update_flag                = Column(String, comment='更新标志')


class BalanceSheet(Base):
    """ 资产负债表 balancesheet_vip """
    __tablename__ = "balance_sheet"
    ts_code_end_date_report_type = Column(String, primary_key=True)
    ts_code       = Column(String, index=True, comment='TS股票代码')
    ann_date      = Column(String, index=True, comment='公告日期')
    f_ann_date    = Column(String, comment='实际公告日期')
    end_date      = Column(String, index=True, comment='报告期')
    report_type   = Column(String, index=True, comment='报表类型')
    comp_type     = Column(String, comment='公司类型')
    end_type      = Column(String, comment='报告期类型')
    total_share          = Column(Float, comment='期末总股本')
    cap_rese             = Column(Float, comment='资本公积金')
    undistr_porfit       = Column(Float, comment='未分配利润')
    surplus_rese         = Column(Float, comment='盈余公积金')
    special_rese         = Column(Float, comment='专项储备')
    money_cap            = Column(Float, comment='货币资金')
    trad_asset           = Column(Float, comment='交易性金融资产')
    notes_receiv         = Column(Float, comment='应收票据')
    accounts_receiv      = Column(Float, comment='应收账款')
    oth_receiv           = Column(Float, comment='其他应收款')
    prepayment           = Column(Float, comment='预付款项')
    div_receiv           = Column(Float, comment='应收股利')
    int_receiv           = Column(Float, comment='应收利息')
    inventories          = Column(Float, comment='存货')
    amor_exp             = Column(Float, comment='长期待摊费用')
    nca_within_1y        = Column(Float, comment='一年内到期的非流动资产')
    sett_rsrv            = Column(Float, comment='结算备付金')
    loanto_oth_bank_fi   = Column(Float, comment='拆出资金')
    premium_receiv       = Column(Float, comment='应收保费')
    reinsur_receiv       = Column(Float, comment='应收分保账款')
    reinsur_res_receiv   = Column(Float, comment='应收分保合同准备金')
    pur_resale_fa        = Column(Float, comment='买入返售金融资产')
    oth_cur_assets       = Column(Float, comment='其他流动资产')
    total_cur_assets     = Column(Float, comment='流动资产合计')
    fa_avail_for_sale    = Column(Float, comment='可供出售金融资产')
    htm_invest           = Column(Float, comment='持有至到期投资')
    lt_eqt_invest        = Column(Float, comment='长期股权投资')
    invest_real_estate   = Column(Float, comment='投资性房地产')
    time_deposits        = Column(Float, comment='定期存款')
    oth_assets           = Column(Float, comment='其他资产')
    lt_rec               = Column(Float, comment='长期应收款')
    fix_assets           = Column(Float, comment='固定资产')
    cip                  = Column(Float, comment='在建工程')
    const_materials      = Column(Float, comment='工程物资')
    fixed_assets_disp    = Column(Float, comment='固定资产清理')
    produc_bio_assets    = Column(Float, comment='生产性生物资产')
    oil_and_gas_assets   = Column(Float, comment='油气资产')
    intan_assets         = Column(Float, comment='无形资产')
    r_and_d              = Column(Float, comment='研发支出')
    goodwill             = Column(Float, comment='商誉')
    lt_amor_exp          = Column(Float, comment='长期待摊费用')
    defer_tax_assets     = Column(Float, comment='递延所得税资产')
    decr_in_disbur       = Column(Float, comment='发放贷款及垫款')
    oth_nca              = Column(Float, comment='其他非流动资产')
    total_nca            = Column(Float, comment='非流动资产合计')
    cash_reser_cb        = Column(Float, comment='现金及存放中央银行款项')
    depos_in_oth_bfi     = Column(Float, comment='存放同业和其它金融机构款项')
    prec_metals          = Column(Float, comment='贵金属')
    deriv_assets         = Column(Float, comment='衍生金融资产')
    rr_reins_une_prem    = Column(Float, comment='应收分保未到期责任准备金')
    rr_reins_outstd_cla  = Column(Float, comment='应收分保未决赔款准备金')
    rr_reins_lins_liab   = Column(Float, comment='应收分保寿险责任准备金')
    rr_reins_lthins_liab = Column(Float, comment='应收分保长期健康险责任准备金')
    refund_depos         = Column(Float, comment='存出保证金')
    ph_pledge_loans      = Column(Float, comment='保户质押贷款')
    refund_cap_depos     = Column(Float, comment='存出资本保证金')
    indep_acct_assets    = Column(Float, comment='独立账户资产')
    client_depos         = Column(Float, comment='其中：客户资金存款')
    client_prov          = Column(Float, comment='其中：客户备付金')
    transac_seat_fee     = Column(Float, comment='其中:交易席位费')
    invest_as_receiv     = Column(Float, comment='应收款项类投资')
    total_assets         = Column(Float, comment='资产总计')
    lt_borr              = Column(Float, comment='长期借款')
    st_borr              = Column(Float, comment='短期借款')
    cb_borr              = Column(Float, comment='向中央银行借款')
    depos_ib_deposits    = Column(Float, comment='吸收存款及同业存放')
    loan_oth_bank        = Column(Float, comment='拆入资金')
    trading_fl           = Column(Float, comment='交易性金融负债')
    notes_payable        = Column(Float, comment='应付票据')
    acct_payable         = Column(Float, comment='应付账款')
    adv_receipts         = Column(Float, comment='预收款项')
    sold_for_repur_fa    = Column(Float, comment='卖出回购金融资产款')
    comm_payable         = Column(Float, comment='应付手续费及佣金')
    payroll_payable      = Column(Float, comment='应付职工薪酬')
    taxes_payable        = Column(Float, comment='应交税费')
    int_payable          = Column(Float, comment='应付利息')
    div_payable          = Column(Float, comment='应付股利')
    oth_payable          = Column(Float, comment='其他应付款')
    acc_exp              = Column(Float, comment='预提费用')
    deferred_inc         = Column(Float, comment='递延收益')
    st_bonds_payable     = Column(Float, comment='应付短期债券')
    payable_to_reinsurer = Column(Float, comment='应付分保账款')
    rsrv_insur_cont      = Column(Float, comment='保险合同准备金')
    acting_trading_sec   = Column(Float, comment='代理买卖证券款')
    acting_uw_sec        = Column(Float, comment='代理承销证券款')
    non_cur_liab_due_1y  = Column(Float, comment='一年内到期的非流动负债')
    oth_cur_liab         = Column(Float, comment='其他流动负债')
    total_cur_liab       = Column(Float, comment='流动负债合计')
    bond_payable         = Column(Float, comment='应付债券')
    lt_payable           = Column(Float, comment='长期应付款')
    specific_payables    = Column(Float, comment='专项应付款')
    estimated_liab       = Column(Float, comment='预计负债')
    defer_tax_liab       = Column(Float, comment='递延所得税负债')
    defer_inc_non_cur_liab = Column(Float, comment='递延收益-非流动负债')
    oth_ncl              = Column(Float, comment='其他非流动负债')
    total_ncl            = Column(Float, comment='非流动负债合计')
    depos_oth_bfi        = Column(Float, comment='同业和其它金融机构存放款项')
    deriv_liab           = Column(Float, comment='衍生金融负债')
    depos                = Column(Float, comment='吸收存款')
    agency_bus_liab      = Column(Float, comment='代理业务负债')
    oth_liab             = Column(Float, comment='其他负债')
    prem_receiv_adva     = Column(Float, comment='预收保费')
    depos_received       = Column(Float, comment='存入保证金')
    ph_invest            = Column(Float, comment='保户储金及投资款')
    reser_une_prem       = Column(Float, comment='未到期责任准备金')
    reser_outstd_claims  = Column(Float, comment='未决赔款准备金')
    reser_lins_liab      = Column(Float, comment='寿险责任准备金')
    reser_lthins_liab    = Column(Float, comment='长期健康险责任准备金')
    indept_acc_liab      = Column(Float, comment='独立账户负债')
    pledge_borr          = Column(Float, comment='其中:质押借款')
    indem_payable        = Column(Float, comment='应付赔付款')
    policy_div_payable   = Column(Float, comment='应付保单红利')
    total_liab           = Column(Float, comment='负债合计')
    treasury_share       = Column(Float, comment='减:库存股')
    ordin_risk_reser     = Column(Float, comment='一般风险准备')
    forex_differ         = Column(Float, comment='外币报表折算差额')
    invest_loss_unconf   = Column(Float, comment='未确认的投资损失')
    minority_int         = Column(Float, comment='少数股东权益')
    total_hldr_eqy_exc_min_int = Column(Float, comment='股东权益合计(不含少数股东权益)')
    total_hldr_eqy_inc_min_int = Column(Float, comment='股东权益合计(含少数股东权益)')
    total_liab_hldr_eqy        = Column(Float, comment='负债及股东权益总计')
    lt_payroll_payable         = Column(Float, comment='长期应付职工薪酬')
    oth_comp_income            = Column(Float, comment='其他综合收益')
    oth_eqt_tools              = Column(Float, comment='其他权益工具')
    oth_eqt_tools_p_shr        = Column(Float, comment='其中:优先股')
    lending_funds              = Column(Float, comment='融出资金')
    acc_receivable             = Column(Float, comment='应收款项')
    st_fin_payable             = Column(Float, comment='应付短期融资款')
    payables                   = Column(Float, comment='应付款项')
    hfs_assets                 = Column(Float, comment='持有待售的资产')
    hfs_sales                  = Column(Float, comment='持有待售的负债')
    cost_fin_assets            = Column(Float, comment='以摊余成本计量的金融资产')
    fair_value_fin_assets      = Column(Float, comment='以公允价值计量且其变动计入其他综合收益的金融资产')
    cip_total                  = Column(Float, comment='在建工程(合计)(元)')
    oth_pay_total              = Column(Float, comment='其他应付款(合计)(元)')
    long_pay_total             = Column(Float, comment='长期应付款(合计)(元)')
    debt_invest                = Column(Float, comment='债权投资(元)')
    oth_debt_invest            = Column(Float, comment='其他债权投资(元)')
    oth_eq_invest              = Column(Float, comment='其他权益工具投资(元)')
    oth_illiq_fin_assets       = Column(Float, comment='其他非流动金融资产(元)')
    oth_eq_ppbond              = Column(Float, comment='其他权益工具:永续债(元)')
    receiv_financing           = Column(Float, comment='应收款项融资')
    use_right_assets           = Column(Float, comment='使用权资产')
    lease_liab                 = Column(Float, comment='租赁负债')
    contract_assets            = Column(Float, comment='合同资产')
    contract_liab              = Column(Float, comment='合同负债')
    accounts_receiv_bill       = Column(Float, comment='应收票据及应收账款')
    accounts_pay               = Column(Float, comment='应付票据及应付账款')
    oth_rcv_total              = Column(Float, comment='其他应收款(合计)（元）')
    fix_assets_total           = Column(Float, comment='固定资产(合计)(元)')
    update_flag                = Column(String, comment='更新标志')


class CashFlow(Base):
    """ 现金流量表 cashflow_vip """
    __tablename__ = "cash_flow"
    ts_code_end_date_report_type = Column(String, primary_key=True)
    ts_code       = Column(String, index=True, comment='TS股票代码')
    ann_date      = Column(String, index=True, comment='公告日期')
    f_ann_date    = Column(String, comment='实际公告日期')
    end_date      = Column(String, index=True, comment='报告期')
    comp_type     = Column(String, comment='公司类型')
    report_type   = Column(String, index=True, comment='报告类型')
    end_type      = Column(String, comment='报告期类型')
    # 经营活动
    net_profit               = Column(Float, comment='净利润')
    finan_exp                = Column(Float, comment='财务费用')
    c_fr_sale_sg             = Column(Float, comment='销售商品、提供劳务收到的现金')
    recp_tax_rends           = Column(Float, comment='收到的税费返还')
    c_fr_oth_operate_a       = Column(Float, comment='收到其他与经营活动有关的现金')
    c_inf_fr_operate_a       = Column(Float, comment='经营活动现金流入小计')
    c_paid_goods_s           = Column(Float, comment='购买商品、接受劳务支付的现金')
    c_paid_to_for_empl       = Column(Float, comment='支付给职工以及为职工支付的现金')
    c_paid_for_taxes         = Column(Float, comment='支付的各项税费')
    oth_cash_pay_oper_act    = Column(Float, comment='支付其他与经营活动有关的现金')
    st_cash_out_act          = Column(Float, comment='经营活动现金流出小计')
    n_cashflow_act           = Column(Float, comment='经营活动产生的现金流量净额')
    im_net_cashflow_oper_act = Column(Float, comment='经营活动产生的现金流量净额(间接法)')
    # 投资活动
    oth_recp_ral_inv_act     = Column(Float, comment='收到其他与投资活动有关的现金')
    c_disp_withdrwl_invest   = Column(Float, comment='收回投资收到的现金')
    c_recp_return_invest     = Column(Float, comment='取得投资收益收到的现金')
    n_recp_disp_fiolta       = Column(Float, comment='处置固定资产、无形资产和其他长期资产收回的现金净额')
    n_recp_disp_sobu         = Column(Float, comment='处置子公司及其他营业单位收到的现金净额')
    stot_inflows_inv_act     = Column(Float, comment='投资活动现金流入小计')
    c_pay_acq_const_fiolta   = Column(Float, comment='购建固定资产、无形资产和其他长期资产支付的现金')
    c_paid_invest            = Column(Float, comment='投资支付的现金')
    n_disp_subs_oth_biz      = Column(Float, comment='取得子公司及其他营业单位支付的现金净额')
    oth_pay_ral_inv_act      = Column(Float, comment='支付其他与投资活动有关的现金')
    n_incr_pledge_loan       = Column(Float, comment='质押贷款净增加额')
    stot_out_inv_act         = Column(Float, comment='投资活动现金流出小计')
    n_cashflow_inv_act       = Column(Float, comment='投资活动产生的现金流量净额')
    # 筹资活动
    c_recp_borrow            = Column(Float, comment='取得借款收到的现金')
    proc_issue_bonds         = Column(Float, comment='发行债券收到的现金')
    oth_cash_recp_ral_fnc_act= Column(Float, comment='收到其他与筹资活动有关的现金')
    stot_cash_in_fnc_act     = Column(Float, comment='筹资活动现金流入小计')
    c_prepay_amt_borr        = Column(Float, comment='偿还债务支付的现金')
    c_pay_dist_dpcp_int_exp  = Column(Float, comment='分配股利、利润或偿付利息支付的现金')
    incl_dvd_profit_paid_sc_ms = Column(Float, comment='其中:子公司支付给少数股东的股利、利润')
    oth_cashpay_ral_fnc_act  = Column(Float, comment='支付其他与筹资活动有关的现金')
    stot_cashout_fnc_act     = Column(Float, comment='筹资活动现金流出小计')
    n_cash_flows_fnc_act     = Column(Float, comment='筹资活动产生的现金流量净额')
    free_cashflow            = Column(Float, comment='企业自由现金流量')
    # 汇率及现金变动
    eff_fx_flu_cash          = Column(Float, comment='汇率变动对现金的影响')
    n_incr_cash_cash_equ     = Column(Float, comment='现金及现金等价物净增加额')
    c_cash_equ_beg_period    = Column(Float, comment='期初现金及现金等价物余额')
    c_cash_equ_end_period    = Column(Float, comment='期末现金及现金等价物余额')
    # 补充资料
    c_recp_cap_contrib       = Column(Float, comment='吸收投资收到的现金')
    incl_cash_rec_saims      = Column(Float, comment='其中:子公司吸收少数股东投资收到的现金')
    uncon_invest_loss        = Column(Float, comment='未确认投资损失')
    prov_depr_assets         = Column(Float, comment='加:资产减值准备')
    depr_fa_coga_dpba        = Column(Float, comment='固定资产折旧、油气资产折耗、生产性生物资产折旧')
    amort_intang_assets      = Column(Float, comment='无形资产摊销')
    lt_amort_deferred_exp    = Column(Float, comment='长期待摊费用摊销')
    decr_deferred_exp        = Column(Float, comment='待摊费用减少')
    incr_acc_exp             = Column(Float, comment='预提费用增加')
    loss_disp_fiolta         = Column(Float, comment='处置固定、无形资产和其他长期资产的损失')
    loss_scr_fa              = Column(Float, comment='固定资产报废损失')
    loss_fv_chg              = Column(Float, comment='公允价值变动损失')
    invest_loss              = Column(Float, comment='投资损失')
    decr_def_inc_tax_assets  = Column(Float, comment='递延所得税资产减少')
    incr_def_inc_tax_liab    = Column(Float, comment='递延所得税负债增加')
    decr_inventories         = Column(Float, comment='存货的减少')
    decr_oper_payable        = Column(Float, comment='经营性应收项目的减少')
    incr_oper_payable        = Column(Float, comment='经营性应付项目的增加')
    others                   = Column(Float, comment='其他')
    conv_debt_into_cap       = Column(Float, comment='债务转为资本')
    conv_copbonds_due_within_1y = Column(Float, comment='一年内到期的可转换公司债券')
    fa_fnc_leases            = Column(Float, comment='融资租入固定资产')
    im_n_incr_cash_equ       = Column(Float, comment='现金及现金等价物净增加额(间接法)')
    net_dism_capital_add     = Column(Float, comment='拆出资金净增加额')
    net_cash_rece_sec        = Column(Float, comment='代理买卖证券收到的现金净额(元)')
    credit_impa_loss         = Column(Float, comment='信用减值损失')
    use_right_asset_dep      = Column(Float, comment='使用权资产折旧')
    oth_loss_asset           = Column(Float, comment='其他资产减值损失')
    end_bal_cash             = Column(Float, comment='现金的期末余额')
    beg_bal_cash             = Column(Float, comment='减:现金的期初余额')
    end_bal_cash_equ         = Column(Float, comment='加:现金等价物的期末余额')
    beg_bal_cash_equ         = Column(Float, comment='减:现金等价物的期初余额')
    is_calc                  = Column(Float, comment='是否为计算值')
    update_flag              = Column(String, comment='更新标志')


class FinaIndicator(Base):
    """ 财务指标数据 fina_indicator_vip """
    __tablename__ = "fina_indicator"
    ts_code_end_date = Column(String, primary_key=True)
    ts_code        = Column(String, index=True, comment='TS股票代码')
    ann_date       = Column(String, index=True, comment='公告日期')
    end_date       = Column(String, index=True, comment='报告期')
    # 每股指标
    eps            = Column(Float, comment='基本每股收益')
    dt_eps         = Column(Float, comment='稀释每股收益')
    total_revenue_ps = Column(Float, comment='每股营业总收入')
    revenue_ps     = Column(Float, comment='每股营业收入')
    capital_rese_ps= Column(Float, comment='每股资本公积')
    surplus_rese_ps= Column(Float, comment='每股盈余公积')
    undist_profit_ps = Column(Float, comment='每股未分配利润')
    extra_item     = Column(Float, comment='非经常性损益')
    profit_dedt    = Column(Float, comment='扣除非经常性损益后的净利润')
    gross_margin   = Column(Float, comment='毛利')
    current_ratio  = Column(Float, comment='流动比率')
    quick_ratio    = Column(Float, comment='速动比率')
    cash_ratio     = Column(Float, comment='保守速动比率')
    invturn_days   = Column(Float, comment='存货周转天数')
    arturn_days    = Column(Float, comment='应收账款周转天数')
    inv_turn       = Column(Float, comment='存货周转率')
    ar_turn        = Column(Float, comment='应收账款周转率')
    ca_turn        = Column(Float, comment='流动资产周转率')
    fa_turn        = Column(Float, comment='固定资产周转率')
    assets_turn    = Column(Float, comment='总资产周转率')
    op_income      = Column(Float, comment='经营活动净收益')
    valuechange_income = Column(Float, comment='价值变动净收益')
    interst_income = Column(Float, comment='利息费用')
    daa            = Column(Float, comment='折旧与摊销')
    ebit           = Column(Float, comment='息税前利润')
    ebitda         = Column(Float, comment='息税折旧摊销前利润')
    fcff           = Column(Float, comment='企业自由现金流量')
    fcfe           = Column(Float, comment='股权自由现金流量')
    current_exint  = Column(Float, comment='无息流动负债')
    noncurrent_exint = Column(Float, comment='无息非流动负债')
    interestdebt   = Column(Float, comment='带息债务')
    netdebt        = Column(Float, comment='净债务')
    tangible_asset = Column(Float, comment='有形资产')
    working_capital= Column(Float, comment='营运资金')
    networking_capital = Column(Float, comment='营运流动资金')
    invest_capital = Column(Float, comment='全部投入资本')
    retained_earnings = Column(Float, comment='留存收益')
    diluted2_eps   = Column(Float, comment='期末摊薄每股收益')
    bps            = Column(Float, comment='每股净资产')
    ocfps          = Column(Float, comment='每股经营活动产生的现金流量净额')
    retainedps     = Column(Float, comment='每股留存收益')
    cfps           = Column(Float, comment='每股现金流量净额')
    ebit_ps        = Column(Float, comment='每股息税前利润')
    fcff_ps        = Column(Float, comment='每股企业自由现金流量')
    fcfe_ps        = Column(Float, comment='每股股权自由现金流量')
    netprofit_margin   = Column(Float, comment='销售净利率')
    grossprofit_margin = Column(Float, comment='销售毛利率')
    cogs_of_sales  = Column(Float, comment='销售成本率')
    expense_of_sales = Column(Float, comment='销售期间费用率')
    profit_to_gr   = Column(Float, comment='净利润/营业总收入')
    saleexp_to_gr  = Column(Float, comment='销售费用/营业总收入')
    adminexp_of_gr = Column(Float, comment='管理费用/营业总收入')
    finaexp_of_gr  = Column(Float, comment='财务费用/营业总收入')
    impai_ttm      = Column(Float, comment='资产减值损失/营业总收入')
    gc_of_gr       = Column(Float, comment='营业总成本/营业总收入')
    op_of_gr       = Column(Float, comment='营业利润/营业总收入')
    ebit_of_gr     = Column(Float, comment='息税前利润/营业总收入')
    roe            = Column(Float, comment='净资产收益率')
    roe_waa        = Column(Float, comment='加权平均净资产收益率')
    roe_dt         = Column(Float, comment='净资产收益率(扣除非经常损益)')
    roa            = Column(Float, comment='总资产报酬率')
    npta           = Column(Float, comment='总资产净利润')
    roic           = Column(Float, comment='投入资本回报率')
    roe_yearly     = Column(Float, comment='年化净资产收益率')
    roa2_yearly    = Column(Float, comment='年化总资产报酬率')
    roe_avg        = Column(Float, comment='平均净资产收益率(增发条件)')
    opincome_of_ebt  = Column(Float, comment='经营活动净收益/利润总额')
    investincome_of_ebt = Column(Float, comment='价值变动净收益/利润总额')
    n_op_profit_of_ebt  = Column(Float, comment='营业外收支净额/利润总额')
    tax_to_ebt     = Column(Float, comment='所得税/利润总额')
    dtprofit_to_profit = Column(Float, comment='扣除非经常损益后的净利润/净利润')
    salescash_to_or= Column(Float, comment='销售商品提供劳务收到的现金/营业收入')
    ocf_to_or      = Column(Float, comment='经营活动产生的现金流量净额/营业收入')
    ocf_to_opincome= Column(Float, comment='经营活动产生的现金流量净额/经营活动净收益')
    capitalized_to_da = Column(Float, comment='资本支出/折旧和摊销')
    debt_to_assets = Column(Float, comment='资产负债率')
    assets_to_eqt  = Column(Float, comment='权益乘数')
    dp_assets_to_eqt = Column(Float, comment='权益乘数(杜邦分析)')
    ca_to_assets   = Column(Float, comment='流动资产/总资产')
    nca_to_assets  = Column(Float, comment='非流动资产/总资产')
    tbassets_to_totalassets = Column(Float, comment='有形资产/总资产')
    int_to_talcap  = Column(Float, comment='带息债务/全部投入资本')
    eqt_to_talcapital = Column(Float, comment='归属于母公司的股东权益/全部投入资本')
    currentdebt_to_debt = Column(Float, comment='流动负债/负债合计')
    longdeb_to_debt= Column(Float, comment='非流动负债/负债合计')
    ocf_to_shortdebt = Column(Float, comment='经营活动产生的现金流量净额/流动负债')
    debt_to_eqt    = Column(Float, comment='产权比率')
    eqt_to_debt    = Column(Float, comment='归属于母公司的股东权益/负债合计')
    eqt_to_interestdebt = Column(Float, comment='归属于母公司的股东权益/带息债务')
    tangibleasset_to_debt = Column(Float, comment='有形资产/负债合计')
    tangasset_to_intdebt  = Column(Float, comment='有形资产/带息债务')
    tangibleasset_to_netdebt = Column(Float, comment='有形资产/净债务')
    ocf_to_debt    = Column(Float, comment='经营活动产生的现金流量净额/负债合计')
    ocf_to_interestdebt = Column(Float, comment='经营活动产生的现金流量净额/带息债务')
    ocf_to_netdebt = Column(Float, comment='经营活动产生的现金流量净额/净债务')
    ebit_to_interest = Column(Float, comment='已获利息倍数(EBIT/利息费用)')
    longdebt_to_workingcapital = Column(Float, comment='长期债务与营运资金比率')
    ebitda_to_debt = Column(Float, comment='息税折旧摊销前利润/负债合计')
    turn_days      = Column(Float, comment='营业周期')
    roa_yearly     = Column(Float, comment='年化总资产净利率')
    roan           = Column(Float, comment='总资产净利率(摊薄)')
    fixed_assets   = Column(Float, comment='固定资产合计')
    profit_prefin_exp = Column(Float, comment='扣除财务费用前的营业利润')
    non_op_profit  = Column(Float, comment='非营业利润')
    op_to_ebt      = Column(Float, comment='营业利润／利润总额')
    nop_to_ebt     = Column(Float, comment='非营业利润／利润总额')
    ocf_to_profit  = Column(Float, comment='经营活动产生的现金流量净额／营业利润')
    cash_to_liqdebt= Column(Float, comment='货币资金／流动负债')
    cash_to_liqdebt_withinterest = Column(Float, comment='货币资金／带息流动负债')
    op_to_liqdebt  = Column(Float, comment='营业利润／流动负债')
    op_to_debt     = Column(Float, comment='营业利润／负债合计')
    roic_yearly    = Column(Float, comment='年化投入资本回报率')
    total_fa_trun  = Column(Float, comment='固定资产合计周转率')
    profit_to_op   = Column(Float, comment='利润总额／营业收入')
    # 单季度指标
    q_opincome     = Column(Float, comment='每股经营活动产生的现金流量净额(单季度)')
    q_investincome = Column(Float, comment='价值变动净收益(单季度)')
    q_dtprofit     = Column(Float, comment='扣除非经常损益后的净利润(单季度)')
    q_eps          = Column(Float, comment='每股收益(单季度)')
    q_netprofit_margin = Column(Float, comment='销售净利率(单季度)')
    q_gsprofit_margin  = Column(Float, comment='毛利率(单季度)')
    q_exp_to_sales = Column(Float, comment='期间费用率(单季度)')
    q_profit_to_gr = Column(Float, comment='净利润／营业总收入(单季度)')
    q_saleexp_to_gr= Column(Float, comment='销售费用／营业总收入(单季度)')
    q_adminexp_to_gr = Column(Float, comment='管理费用／营业总收入(单季度)')
    q_finaexp_to_gr  = Column(Float, comment='财务费用／营业总收入(单季度)')
    q_impair_to_gr_ttm = Column(Float, comment='资产减值损失／营业总收入(单季度)')
    q_gc_to_gr     = Column(Float, comment='营业总成本／营业总收入(单季度)')
    q_op_to_gr     = Column(Float, comment='营业利润／营业总收入(单季度)')
    q_roe          = Column(Float, comment='净资产收益率(单季度)')
    q_dt_roe       = Column(Float, comment='净资产单季度收益率(扣除非经常损益)')
    q_npta         = Column(Float, comment='总资产净利润(单季度)')
    q_ocf_to_sales = Column(Float, comment='经营活动产生的现金流量净额/营业收入(单季度)')
    q_ocf_to_or    = Column(Float, comment='经营活动产生的现金流量净额/经营活动净收益(单季度)')
    basic_eps_yoy  = Column(Float, comment='基本每股收益同比增长率')
    dt_eps_yoy     = Column(Float, comment='稀释每股收益同比增长率')
    cfps_yoy       = Column(Float, comment='每股经营活动产生的现金流量净额同比增长率')
    op_yoy         = Column(Float, comment='营业利润同比增长率')
    ebt_yoy        = Column(Float, comment='利润总额同比增长率')
    netprofit_yoy  = Column(Float, comment='归属母公司股东的净利润同比增长率')
    ocf_yoy        = Column(Float, comment='经营活动产生的现金流量净额同比增长率')
    roe_yoy        = Column(Float, comment='净资产收益率同比增长率')
    bps_yoy        = Column(Float, comment='每股净资产相对年初增长率')
    assets_yoy     = Column(Float, comment='资产总计相对年初增长率')
    eqt_yoy        = Column(Float, comment='归属母公司的股东权益相对年初增长率')
    tr_yoy         = Column(Float, comment='营业总收入同比增长率')
    or_yoy         = Column(Float, comment='营业收入同比增长率')
    equity_yoy     = Column(Float, comment='净资产同比增长率')
    rd_exp         = Column(Float, comment='研发费用')
    update_flag    = Column(String, comment='更新标志')


class FinaForecast(Base):
    """ 业绩预告 forecast_vip """
    __tablename__ = "fina_forecast"
    ts_code_ann_date_end_date = Column(String, primary_key=True)
    ts_code         = Column(String, index=True, comment='TS股票代码')
    ann_date        = Column(String, index=True, comment='公告日期')
    end_date        = Column(String, index=True, comment='报告期')
    type            = Column(String, comment='业绩预告类型')
    p_change_min    = Column(Float, comment='预告净利润变动幅度下限（%）')
    p_change_max    = Column(Float, comment='预告净利润变动幅度上限（%）')
    net_profit_min  = Column(Float, comment='预告净利润下限（万元）')
    net_profit_max  = Column(Float, comment='预告净利润上限（万元）')
    last_parent_net = Column(Float, comment='上年同期归属母公司净利润')
    first_ann_date  = Column(String, comment='首次公告日')
    summary         = Column(String, comment='业绩预告摘要')
    change_reason   = Column(String, comment='业绩变动原因')


class FinaExpress(Base):
    """ 业绩快报 express_vip """
    __tablename__ = "fina_express"
    ts_code_ann_date_end_date = Column(String, primary_key=True)
    ts_code       = Column(String, index=True, comment='TS股票代码')
    ann_date      = Column(String, index=True, comment='公告日期')
    end_date      = Column(String, index=True, comment='报告期')
    revenue       = Column(Float, comment='营业收入(元)')
    operate_profit= Column(Float, comment='营业利润(元)')
    total_profit  = Column(Float, comment='利润总额(元)')
    n_income      = Column(Float, comment='净利润(元)')
    total_assets  = Column(Float, comment='总资产(元)')
    total_hldr_eqy_exc_min_int = Column(Float, comment='股东权益合计(不含少数股东权益)(元)')
    diluted_eps   = Column(Float, comment='每股收益(摊薄)(元)')
    diluted_roe   = Column(Float, comment='净资产收益率(摊薄)(%)')
    yoy_net_profit= Column(Float, comment='去年同期修正后净利润')
    bps           = Column(Float, comment='每股净资产')
    yoy_sales     = Column(Float, comment='同比增长率:营业收入')
    yoy_op        = Column(Float, comment='同比增长率:营业利润')
    yoy_tp        = Column(Float, comment='同比增长率:利润总额')
    yoy_dedu_np   = Column(Float, comment='同比增长率:归属母公司股东的净利润')
    yoy_eps       = Column(Float, comment='同比增长率:基本每股收益')
    yoy_roe       = Column(Float, comment='同比增长率:加权平均净资产收益率')
    growth_assets = Column(Float, comment='比年初增长率:总资产')
    yoy_equity    = Column(Float, comment='比年初增长率:归属母公司的股东权益')
    growth_bps    = Column(Float, comment='比年初增长率:归属于母公司股东的每股净资产')
    or_last_year  = Column(Float, comment='去年同期营业收入')
    op_last_year  = Column(Float, comment='去年同期营业利润')
    tp_last_year  = Column(Float, comment='去年同期利润总额')
    np_last_year  = Column(Float, comment='去年同期净利润')
    eps_last_year = Column(Float, comment='去年同期每股收益')
    open_net_assets = Column(Float, comment='期初净资产')
    open_bps      = Column(Float, comment='期初每股净资产')
    perf_summary  = Column(String, comment='业绩简要说明')
    is_audit      = Column(Float, comment='是否审计(1是 0否)')
    remark        = Column(String, comment='备注')


class Dividend(Base):
    """ 分红送股 dividend """
    __tablename__ = "dividend"
    ts_code_end_date_div_proc = Column(String, primary_key=True)
    ts_code       = Column(String, index=True, comment='TS股票代码')
    end_date      = Column(String, index=True, comment='分红年度')
    ann_date      = Column(String, index=True, comment='预案公告日')
    div_proc      = Column(String, comment='实施进度')
    stk_div       = Column(Float, comment='每股送转')
    stk_bo_rate   = Column(Float, comment='每股送股比例')
    stk_co_rate   = Column(Float, comment='每股转增比例')
    cash_div      = Column(Float, comment='每股分红（税后）')
    cash_div_tax  = Column(Float, comment='每股分红（税前）')
    record_date   = Column(String, comment='股权登记日')
    ex_date       = Column(String, index=True, comment='除权除息日')
    pay_date      = Column(String, comment='派息日')
    div_listdate  = Column(String, comment='红股上市日')
    imp_ann_date  = Column(String, comment='实施公告日')
    base_date     = Column(String, comment='基准日')
    base_share    = Column(Float, comment='基准股本（万）')


class FinaAudit(Base):
    """ 财务审计意见 fina_audit """
    __tablename__ = "fina_audit"
    ts_code_end_date = Column(String, primary_key=True)
    ts_code      = Column(String, index=True, comment='TS股票代码')
    ann_date     = Column(String, index=True, comment='公告日期')
    end_date     = Column(String, index=True, comment='报告期')
    audit_result = Column(String, comment='审计结果')
    audit_fees   = Column(Float, comment='审计总费用（元）')
    audit_agency = Column(String, comment='会计事务所')
    audit_sign   = Column(String, comment='签字会计师')


class FinaMainbz(Base):
    """ 主营业务构成 fina_mainbz_vip """
    __tablename__ = "fina_mainbz"
    ts_code_end_date_bz_item_curr_type = Column(String, primary_key=True)
    ts_code   = Column(String, index=True, comment='TS股票代码')
    end_date  = Column(String, index=True, comment='报告期')
    bz_item   = Column(String, comment='主营业务来源')
    bz_sales  = Column(Float, comment='主营业务收入(元)')
    bz_profit = Column(Float, comment='主营业务利润(元)')
    bz_cost   = Column(Float, comment='主营业务成本(元)')
    curr_type = Column(String, comment='货币代码')
    update_flag = Column(String, comment='更新标志')


class DisclosureDate(Base):
    """ 财报披露日期 disclosure_date """
    __tablename__ = "disclosure_date"
    ts_code_end_date = Column(String, primary_key=True)
    ts_code      = Column(String, index=True, comment='TS代码')
    ann_date     = Column(String, index=True, comment='最新披露公告日')
    end_date     = Column(String, index=True, comment='报告期')
    pre_date     = Column(String, comment='预计披露日期')
    actual_date  = Column(String, comment='实际披露日期')
    modify_date  = Column(String, comment='披露日期修正记录')
